export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS  = "GET_ALL_ORDERS_REQUEST_SUCCESS";
export const GET_ALL_ORDERS_FAIL  = "GET_ALL_ORDERS_REQUEST_FAIL";

export const GET_CUSTOMER_ORDERS_REQUEST = "GET_CUSTOMER_ORDERS_REQUEST";
export const GET_CUSTOMER_ORDERS_SUCCESS  = "GET_CUSTOMER_ORDERS_REQUEST_SUCCESS";
export const GET_CUSTOMER_ORDERS_FAIL  = "GET_CUSTOMER_ORDERS_REQUEST_FAIL";

export const GET_FILTERED_ORDERS_REQUEST = "GET_FILTERED_ORDERS_REQUEST";
export const GET_FILTERED_ORDERS_SUCCESS  = "GET_FILTERED_ORDERS_REQUEST_SUCCESS";
export const GET_FILTERED_ORDERS_FAIL  = "GET_FILTERED_ORDERS_REQUEST_FAIL";

export const BUY_ITEMS_REQUEST  = "BUY_ITEMS_REQUEST";
export const BUY_ITEMS_SUCCESS  = "BUY_ITEMS_SUCCESS";
export const BUY_ITEMS_FAIL  = "BUY_ITEMS_FAIL";

export const ADD_ITEM_TO_CART  = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART  = "REMOVE_ITEM_FROM_CART";
export const DELETE_ORDER  = "DELETE_ORDER";

export const CANCEL_PURCHASE_REQUEST  = "CANCEL_PURCHASE_REQUEST";
export const CANCEL_PURCHASE_SUCCESS  = "CANCEL_PURCHASE_SUCCESS";
export const CANCEL_PURCHASE_FAIL  = "CANCEL_PURCHASE_FAIL";

export const CANCEL_PURCHASE_URL  = "api/order/delete-order";
export const GET_ALL_ORDERS_URL = 'api/Order/my-orders'
export const GET_FILTERED_ORDERS_URL = 'api/Order/filter-by-status'
export const BUY_ITEMS_URL = 'api/Order/create-order'




export const cenaDostave = 3